# Generated by Django 4.1.7 on 2023-03-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('f_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('estado', models.IntegerField(verbose_name=9)),
            ],
            options={
                'db_table': 'Trabajador',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('estado', models.IntegerField()),
                ('id_Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.trabajador')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.BinaryField()),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuarios')),
            ],
            options={
                'db_table': 'Pais',
            },
        ),
    ]
